### PR TITLE
Add kustomize support (and dedupicate the hell out of it)

### PR DESCRIPTION
**Pull request by blaggacao**
**What has changed?**

- Deduplicate, deduplicate, deduplicate
- Cleanup of `./services/**/k8s/*`
- Added `kustomization.yaml` so that components can be consumed flexibly downstream
- Does _not_ break `kubectl apply -f` based workflows. Though some inconsistencies (bugs?) encountered eventually might need conflict resolution downstream.

**Does a specific change require especially careful review?**

Please review each commit. I did most of the changes with some advanced command line witchery, but there was a point when diffing minikube against services where some _real_ inconsistencies where uncovered, for example a fix here, but not there and stuff like that. Now that the environment variables are in their own config files, it should be really easy for a person familair with the environment variables to spot if everything is in order with `cat services/**/configmap.yaml` and `cat services/**/secret.yaml` &mdash; no more indirection and named references: plain variables!
 
- Change X
  - Because there are too much sources of truth. This makes the whole project difficult to handle &mdash; and I'm sure it has caused churn down the line.
  - all kubernetes artefacts under `./platform` & `./services`

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

- [ ] rebuilt a working sample of `./minikube` as it was &mdash; with overlay in `./deploy`
- [ ] rebuilt a working sample of `./services` as it was &mdash; with overlay in `./deploy`
- [ ] extracted commits that would make a good marginal PR on their own (some fixes I encountered during the journey or general linting) &mdash; then rebase.
- [ ] asked OIH developer to _kustomize + diff_ resources off this branch against a running local dev cluster and received diff &mdash; incorporated results
- [ ] asked OIH sysadmin to _kustomize + diff_ against a running instance using `./services`, got the diff and fixed things that should have moved out of fixture
- [ ] rebased on master without DevShell &mdash; I used it for my personal workflows during dev.
- [ ] relocated and adapted `./minikube` instructions permanently to the `./deploy/overlay/dev` place
- [ ] found, implemented and documented an interim solution for the service account seeding (_just reapply?_) &mdash; proper: use SPIFFE workload attestation or similar solution

**Planned to be extracted &mdash; rebasing fun hello https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/ffe8ddb878af5faf2559a2da2a8f8bc1cf5bb0fb!**
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/4e6c1b60703eb1cffe3de2125e2a3762145cf4de
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/ff1ba03fb555b1328d751875830a3f4f74a56318
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/2fff8fbf7e325b40b2b892b22cb0df5962fef4b5
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/5b034faece6e36c724784beab11d237f07a3175c
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/d2c504ec9c7ce5a5f13e9ba2657b0eb4db96f12d
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/7e5c85429817b6840c2c4f4915dbf575ac080a1d
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/056d154bcf0e42390bb5c5fac46505bc918d7ea7
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/be5dbb553afbd92712ab28ef13e5327961f8a908 (is it?)
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/d22f3aa8d18c6a567ecdd7aef739aae80290920e (makes more sense to not deviate from the crowd!?)
- https://github.com/openintegrationhub/openintegrationhub/pull/1041/commits/dee6ec867a017da5ab2ebed1cb9c374ed891b82b (it helped with the bash wizardry tooling to work on homogenized yamls)

---

### Daumenkino `apps/v1:Deployment` :smile: 

out

---

### Daumenkino `v1:Secret` :+1: 
out

Those _Secrets_ can easily and cleanly be merged, overridden and / or replaced with custom _Secrets_.

---

### Daumenkino `v1:ConfigMap` :microscope: 
out

Those _ConfigMaps_ can easily and cleanly be merged, overridden and / or replaced with custom _ConfigMaps_.

---

#### Generators! &mdash; directly from source configmaps / secrets | no more code duplication :pray: 
image

---

#### DevOps immediately find their way arround

image
---
image

### CODE REVIEW

**Comment by blaggacao** [comment]
#### Daumenkino :smile: 

out

**Comment by blaggacao** [comment]
#### Daumenkino `v1/Secrets` :+1: 
out

**Comment by blaggacao** [comment]
### Daumenkino `v1:ConfigMap` :microscope: 
out

**Comment by blaggacao** [comment]
#### Generators! &mdash; directly from source configmaps / secrets | no more code duplication :pray: 
image

**Comment by blaggacao** [comment]
#### DevOps see immediately what ought to be modified
image

**Comment by heggert** [comment]
Changes are too far behind the current master branch. Please provide additional fixes to ensure compatibility.

**Pull request closed without merging**
