### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by fdegenhr**

### CODE REVIEW

**Comment by philecs** [comment]
@fdegenhr and @hschmidthh any updates here?

**Comment by philecs** [comment]
@falkvoigt and @hschmidthh any updates on this PR?

**Comment by philecs** [comment]
@falkvoigt and @hschmidthh any updates on this PR?

**Comment by falkvoigt** [comment]
That changes have no impacted on the service or the deployment ist's just for local testing. so please Merge as you want to

**Pull request closed without merging**
