### PR TITLE
Webhooks HMAC Auth Fix

### PR DESCRIPTION
**Pull request by BirdHighway**
**What has changed?**

- HMAC data is sent to secret service for validation via `POST` request as a `base64` encoded string
- `DEFAULT_HMAC_ALGORITHM` is set to `sha256`
- HMAC is verified when specified by `flowSettings`, not based on presence / absence of HMAC header

**Does a specific change require especially careful review?**
No, other than making sure existing functionality is not affected by these changes.

**What is still open or a known issue?**
No other known issues. Closes issue #1452 

**Release Notes**
Fixes issue with webhooks HMAC authentication

### CODE REVIEW

**Comment by weberjm** [comment]
Robb and I had debated when to enforce the HMAC header and had decided on trying to auth with it whenever it is provided. I think what you have done is a better solution, that puts the enfocement power on the flow settings.

Regarding the switch on the rawBody, can you give a bit more info on what/why it was done? I thought we had both tested and things were working there. I do see that rawBody was previously set as a Buffer, and the process you are implementing here is
- Converting rawBody from a Buffer to a base64 string
- Passing to Secret Service, to validate HMAC
- parsing the rawBody back to a Buffer
- then converting the Buffer back to a String

The final step might also be unnecessary, since the `<hmac>.update()` function can already [accept Buffers](https://nodejs.org/api/crypto.html#hmacupdatedata-inputencoding). Did you run into specific instances where this is failing? i.e. is this a separate use case for a new service, where their body formatted fifferently, or was this a bug from the beginning?

**Comment by BirdHighway** [comment]
Back in November Robb had asked me to verify that the webhooks auth was working, and I told him it was, but I don't think I tested it properly / I may have been mistaken about whether it worked as intended.

As far as the rawBody conversions - it sounds like I added in additional unnecessary work! Let me take a look to make sure I'm not missing something, but I think I probably just added changes in the process of debugging and didn't properly question whether they were necessary once I got it to work.

**Comment by BirdHighway** [comment]
So `rawBody` is initially a buffer when we first have access to it in the webhooks service. We need to send this buffer to the secret service as part of a JSON request that includes other pieces of information that we need (like the `hmacValue` and `hmacAlgo`).

The output of calling `JSON.stringify()` on a buffer is an object that contains an array with the buffer data converted to an array of ints:
```json
{"type":"Buffer","data":[123,34,97,98,99,34,58,49,50,51,125]}
```

On the other end of the request, in the secret service, we parse the incoming JSON, select the `data` array and convert that to a buffer again with `Buffer.from(data)`.  This approach definitely works and has the advantage that it might be a little less convoluted. Here's a comparison of that approach with the pull request I made: https://github.com/blendededge/openintegrationhub/compare/webhooks-hmac...blendededge:openintegrationhub:webhooks-hmac-buffer

(The `<hmac>.update()` function can accept a buffer, but not a normal array, which generates the error: `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array.`)

The only real advantage I see to sending the `rawBody` as base64 encoded data is that it is more efficient. For example the data `{"abc": 123}` becomes:
- `"eyJhYmMiOiAxMjN9"` in base64 (16 bytes over the wire)
- `"123,34,97,98,99,34,58,32,49,50,51,125"` as an array (37 bytes over the wire)

If we weren't sending data over the network as a (JSON) string keeping everything as a buffer would be much more efficient. But with it having to be converted to a string I think it's less clear cut.

**Comment by weberjm** [comment]
Thanks for the detailed review. I also don't see a huge advantage to choosing one over the other: a very slight processing time improvement from not having to encode and decode from base64, versus body size in the network transmission. It might just be a wash, there.

If you prefer to leave base64, then, I can approve it that way. If I am not mistaken, the removal of the toString() function inside the update() would still be beneficial, though, yes?

**Comment by BirdHighway** [comment]
The current use of the `.toString()` method is necessary because the base64 has to be converted to utf-8 (the assumed original encoding of the data sent to the webhooks endpoint). Without converting `.toString()` the validation will fail. There may well be a smoother way to do this, but I'm not sure what it would be.

**Comment by BirdHighway** [comment]
If the two approaches are roughly equal, I would vote for the approach that changes the existing code the least, which could be something like this:
https://github.com/openintegrationhub/openintegrationhub/compare/master...blendededge:openintegrationhub:webhooks-hmac-buffer

**Comment by weberjm** [comment]
That's right. Even though both representations are the same string, they would give different HMAC values because of the encoding.

As I said above, I think the difference between processing a Buffer and a base64 string are probably minimal, so you are welcome to add in the last changes if that is your preference. Just let me know when the PR is ready, and I will merge it.

**Comment by BirdHighway** [comment]
Okay thank you, it is ready to merge.

**Pull request merged**
