### PR TITLE
Adjusted ICR to be compatible with CircleCi

### PR DESCRIPTION
**Pull request by SvenHoeffler**
Largely identical with the changes made by Falk, minor changes to ICR to work with the new testing environment.

### CODE REVIEW

**Comment by philecs** [comment]
@SvenHoeffler iam-tests currently fail. Any ideas?

**Comment by SvenHoeffler** [comment]
> @SvenHoeffler iam-tests currently fail. Any ideas?

Apparently, that is an IAM-internal issue with its test suites from before work started on CircleCI. I think it's already been fixed in Falk's branch: https://github.com/openintegrationhub/openintegrationhub/tree/%23171-IAM-Pipeline

**Comment by falkvoigt** [comment]
Yes it's fixed in My branch!

**Comment by philecs** [comment]
@falkvoigt are you still working on this branch or can we merge it to fix the failed check?

**Comment by falkvoigt** [comment]
Not yet. Pavel needs to put in the elasticIO Services. otherwise we will override the old config and the services will not be build or will Build but not tested :)

**Comment by philecs** [comment]
Thanks for the update :) @pnedelko I guess you are already informed?

**Comment by SvenHoeffler** [comment]
Merged the changes from the most recent master, Tests pass now.

**Review by philecs — APPROVED** [review]

**Pull request merged**
