### PR TITLE
New icr structure

### PR DESCRIPTION
**Pull request by hschmidthh**
this is a complete new version of the icr

### CODE REVIEW

**Comment by philecs** [comment]
@falkvoigt and @hschmidthh any updates on this PR?

**Comment by philecs** [comment]
@falkvoigt and @hschmidthh any updates on this PR?

**Comment by philecs** [comment]
@falkvoigt and @hschmidthh any updates on this PR?

**Comment by falkvoigt** [comment]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Comment by falkvoigt** [comment]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Comment by falkvoigt** [comment]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Review by falkvoigt — APPROVED** [review]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Review by falkvoigt — COMMENTED** [review]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Review by falkvoigt — APPROVED** [review]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Review by falkvoigt — COMMENTED** [review]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Comment by falkvoigt** [comment]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Review by falkvoigt — APPROVED** [review]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Review by falkvoigt — APPROVED** [review]
I just resolved some conflicts in package.json but that was not the Problem. PR wasn't goog because of Problems in the test Cluster.

**Comment by philecs** [comment]
Any updates here @falkvoigt ?

**Comment by philecs** [comment]
Any updates here @falkvoigt ?

**Comment by falkvoigt** [comment]
Github errors :) seems they queued all my comments :) i will merge the PR

**Pull request merged**
